### PR TITLE
Added Input Form

### PR DESCRIPTION
**Pull request by marlonmountjoy**
I did this for a school project, I'm very new to git so struggling a bit, my apologies. Hopefully I forked this properly but I'm not sure
[BookShelf.zip](https://github.com/petargyurov/virtual-bookshelf/files/8674384/BookShelf.zip)
.

### CODE REVIEW

**Comment by marlonmountjoy** [comment]
hey I fixed a few things and added some error handling, I have my version hosted at marlonmountjoy@github.io if u wanna check it out here's an updated zip as we
[BookShelf.zip](https://github.com/petargyurov/virtual-bookshelf/files/8682861/BookShelf.zip)
l

**Comment by petargyurov** [comment]
Hey Marlon. Thank you for the pull request. 

Your input form looks great! However, I think a feature like this is too custom and goes beyond the scope of this (tiny) project. The idea is that this repo acts as a basic building block; keeping it simple means anyone can integrate into their work in a way that works for them, just like you have. 

I'm going to close this PR but feel free to comment. Definitely keep working on your implementation of this and let me know if I can help in any way.

**Comment by marlonmountjoy** [comment]
Ya I understand, I was just playing around and wanted an ez way to send u my projecto. I do have a couple questions if you are willing to answer:
QuestionOne: I want to use cookies or local storage to store the divs after they are inserted, can you give any feeback?
QuestionTwo: Was my fork/pull request done correctly, could you have merged my submission?

**Comment by petargyurov** [comment]
Sure.

1) Local Storage would work OK for this but keep in mind that it would obviously only work per-browser and you could easily lose all that data if you clear your local storage. I wouldn't "store the divs" per se: I would save the book data as an object and stringify it (because localstorage only accepts strings). For example:
```javascript
var books = [];
var book = {title:"Your book title", author: "Book author", cover: "https://....."};
books.push(book)

// store the books
localStorage.setItem('books', JSON.stringify(books));

// get books
var books = JSON.parse(localStorage.getItem('books'));
```

2) Yep it looks like you did things right. My only note would be that some files shouldn't have been commited. Files such as:

- .vs/ProjectSettings.json
- .vs/VSWorkspaceState.json
- .vs/slnx.sqlite
- .vs/virtual-bookshelf/config/applicationhost.config
- .vs/virtual-bookshelf/v16/.suo
- virtual-bookshelf.sln

I assume you're using Visual Studio: lots of these are project config files that are only relevant for your local development. Otherwise you're all good!

**Pull request closed without merging**
